src/partials/hero/hero.html
added to mail link
href="lloydjefferson@gmail.com?subject=Subject%20of%20email&body=Message%20text&cc=ccuser@example.com&bcc=bccuser@example.com"
=> added mailto subject and body

src/partials/hero/hero.html
href="mailto:user@example.com?subject=Subject%20of%20email&amp;body=Message%20text&amp;cc=ccuser@example.com&amp;bcc=bccuser@example.com"
=> changed href in mailto

src/assets/css/reset.css
=> remove from reset input

src/assets/css/reset.css
input:focus {
outline: none;
}
=> added outline: none to input

src/assets/css/base.css
/* Mobile_Desktop_Tablet/H5 */
.header-5 {
font-size: 20px;
font-weight: 600;
line-height: 1.5;
letter-spacing: -0.02em;
}
=> changed h5 styles in base.css file

src/assets/svg/icons.svg, src/partials/about-me/about-me.css, src/partials/about-me/about-me.html
Also I added two <symbol> elements in file icons.svg with strokes removed.
=> html + css

src/assets/svg/icons.svg, src/partials/about-me/about-me.css, src/partials/about-me/about-me.html, src/partials/about-me/about-me.js
Accordion + corrections in icons.svg,css,html. 
New in file js
=> Accordion + corrections in icons.svg,css,html.

src/partials/work-together/work-together.html, src/partials/work-together/work-together.js
=> minor bug fix

src/partials/about-me/about-me.css, src/partials/about-me/about-me.html, src/partials/about-me/accordion.js, src/partials/about-me/swiper.js
Update swiper, accordion, html, css
=> Update swiper, accordion, html, css

src/partials/about-me/accordion.js, src/partials/about-me/swiper.js
some corrections accordion, swiper
=> some corrections accordion,swiper

src/partials/header/header.css, src/partials/header/header.html, src/partials/header/header.js
=> fix-is-open

src/partials/about-me/about-me.css, src/partials/about-me/about-me.html, src/partials/about-me/accordion.js, src/partials/about-me/swiper.js
=> fix swiper and accordion

src/partials/reviews/reviews.js
=> Workaround to fix Nelli section

src/partials/about-me/about-me.css, src/partials/about-me/about-me.html
=> fix circles

src/partials/projects/projects.css, src/partials/projects/projects.html, src/partials/projects/projects.js
- Added animation for the slider.
- Links are opening.
- Lists for similar elements.
- Removed unnecessary divs.
- Corrected spacing between adjacent elements.
- Replaced project images with tablet and desktop versions.
=> projects-fix

src/partials/about-me/about-me.html, src/partials/about-me/swiper.js, src/partials/scroll-to-top-btn/scroll-to-top-btn.css
=> btn+animation + swiper

src/partials/about-me/about-me.html
=> little correction in aos

src/partials/projects/projects.css, src/partials/projects/projects.js
- The slider now responds to swiping on touchscreen devices.
- Fixed padding according to the design.
- Animations have become smoother.
- Hover and focus effects are disabled on the disabled button.
=> projects-enhanced

src/partials/projects/projects.css, src/partials/projects/projects.js
The animation has become smoother
=> project-animation-enhancemen

src/partials/scroll-to-top-btn/scroll-to-top-btn.css
=> update btn scroll

src/partials/about-me/about-me.css
fixed smooth closing and opening
=> fix padding
